import os
import json
from fastapi import FastAPI
from orchestrator.main_orchestrator import MainOrchestrator

app = FastAPI(
    title="HI-NEXUS Gateway",
    description="Hyperinsulinism Intelligence Network for Universal eXploration & Solutions Gateway",
    version="1.0.0"
)
orch = MainOrchestrator()

# Establish path to data
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(BASE_DIR, "..", "data", "hi_nexus_data.json")

def load_json(file_path: str) -> dict:
    try:
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                return json.load(f)
    except Exception:
        pass
    return {}

@app.get("/")
def root():
    return {
        "status": "HI-NEXUS running",
        "description": "Hyperinsulinism Intelligence Network API - Operational MVP Phase 1"
    }

@app.get("/run")
def run(goal: str):
    """
    Executes the fully functional, 100% operational multi-agent sequential pipeline
    (Wikipedia live summary fetch -> Curated Variant Matching -> Subprocess Sandbox testing)
    and returns a structured, verified diagnostic JSON payload.
    """
    # 1. Trigger the real multi-agent pipeline
    pipeline_results = orch.run(goal)
    
    # Extract raw outputs
    wiki_extract = pipeline_results.get("research", "No info found")
    bio_json_str = pipeline_results.get("bio", "{}")
    sandbox_log = pipeline_results.get("dev", "No testing logged")
    
    # 2. Safely parse the 100% factual JSON generated by the BioAgent
    try:
        bio_info = json.loads(bio_json_str)
    except Exception:
        bio_info = {"error": "Failed to parse biological profile", "raw_payload": bio_json_str}
        
    # 3. Assemble the ultimate real-world structured clinical diagnostic payload
    clinical_payload = {
        "query": goal,
        "gene": bio_info.get("gene", "Unknown"),
        "full_name": bio_info.get("full_name", "N/A"),
        "molecular_function": bio_info.get("molecular_function", "N/A"),
        "clinical_relevance": bio_info.get("clinical_impact", "N/A"),
        "classification": {
            "responsiveness": bio_info.get("diazoxide_responsiveness", "UNKNOWN"),
            "therapies_recommended": bio_info.get("recommended_therapies", []),
        },
        "variants_cataloged": bio_info.get("cataloged_pathogenic_variants", []),
        "wikipedia_extract": wiki_extract,
        "sandbox_verification": sandbox_log
    }
    
    return clinical_payload

@app.get("/api/data")
def get_all_data():
    return load_json(DATA_PATH)

@app.get("/api/modules")
def get_modules():
    return load_json(DATA_PATH).get("modules", [])

@app.get("/api/staff")
def get_staff():
    return load_json(DATA_PATH).get("staff", [])

@app.get("/api/phases")
def get_phases():
    return load_json(DATA_PATH).get("phases", [])
